export default [
  {
    id: '1',
    type: 0,
    isMobile: false,
    style: {
      backgroundImage: 'url("/df-1.jpg")',
      height: '100vh',
      backgroundAttachment: 'fixed',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      textAlign: 'center',
    },
    mobileStyle: {
      backgroundImage: 'url("/df-1-mobile.jpg")',
      height: '100vh',
      backgroundAttachment: 'fixed',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      textAlign: 'center',
    },
    content: '「 命由己造，相由心生 」',
    order: 1,
  },
  {
    id: '2',
    type: 1,
    style: {
      backgroundColor: '#000',
      height: '20vh',
      textAlign: 'center',
    },
    content: 'HARDER',
    order: 2,
  },
  {
    id: '3',
    type: 0,
    isMobile: false,
    style: {
      backgroundImage: 'url("/br-1.jpg")',
      height: '100vh',
      backgroundAttachment: 'fixed',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      textAlign: 'center',
    },
    mobileStyle: {
      backgroundImage: 'url("/br-1-mobile.jpg")',
      height: '100vh',
      backgroundAttachment: 'fixed',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      textAlign: 'center',
    },
    content: '「 认识自我 」',
    order: 3,
  },
  {
    id: '4',
    type: 1,
    style: {
      backgroundColor: '#000',
      height: '20vh',
      textAlign: 'center',
    },
    content: 'BETTER',
    order: 4,
  },
  {
    id: '5',
    type: 0,
    isMobile: false,
    style: {
      backgroundImage: 'url("/m-1.jpg")',
      height: '100vh',
      backgroundAttachment: 'fixed',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      textAlign: 'center',
    },
    mobileStyle: {
      backgroundImage: 'url("/m-1-mobile.jpg")',
      height: '100vh',
      backgroundAttachment: 'fixed',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      textAlign: 'center',
    },
    content: '「 保持赤子之心 」',
    order: 5,
  },
  {
    id: '6',
    type: 1,
    style: {
      backgroundColor: '#000',
      height: '20vh',
      textAlign: 'center',
    },
    content: 'FASTER',
    order: 6,
  },
  {
    id: '7',
    type: 0,
    isMobile: false,
    style: {
      backgroundImage: 'url("/csgo-2.jpg")',
      height: '50vh',
      backgroundAttachment: 'fixed',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      textAlign: 'center',
    },
    mobileStyle: {
      backgroundImage: 'url("/csgo-2-mobile.jpg")',
      height: '100vh',
      backgroundAttachment: 'fixed',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      textAlign: 'center',
    },
    content: '「 用枪支粉碎生活的虚伪 」',
    order: 7,
  },
  {
    id: '8',
    type: 0,
    isMobile: false,
    style: {
      backgroundImage: 'url("/csgo-1.jpg")',
      height: '50vh',
      backgroundAttachment: 'fixed',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      textAlign: 'center',
    },
    mobileStyle: {
      backgroundImage: 'url("/csgo-1-mobile.jpg")',
      height: '100vh',
      backgroundAttachment: 'fixed',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      textAlign: 'center',
    },
    content: '「 用友情诠释生命的真谛 」',
    order: 8,
  },
  {
    id: '9',
    type: 1,
    style: {
      backgroundColor: '#000',
      height: '20vh',
      textAlign: 'center',
    },
    content: 'STRONGER',
    order: 9,
  },
  {
    id: '10',
    type: 0,
    isMobile: false,
    style: {
      backgroundImage: 'url("/dp-end.jpg")',
      height: '100vh',
      backgroundAttachment: 'fixed',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      textAlign: 'center',
    },
    mobileStyle: {
      backgroundImage: 'url("/dp-end.jpg")',
      height: '100vh',
      backgroundAttachment: 'fixed',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundSize: 'cover',
      textAlign: 'center',
    },
    content: '',
    order: 10,
  },
]
