export default [
  {
    id: '1',
    parentId: '0',
    name: 'home',
    routerPath: '/cloudable',
    title: '首页',
    disabled: false,
    icon: 'el-icon-s-home',
    type: 3,
  },
  {
    id: '2',
    parentId: '0',
    name: 'blog',
    routerPath: '/cloudable/blog',
    title: '个人博客',
    disabled: false,
    icon: 'el-icon-reading',
    type: 3,
  },
  {
    id: '3',
    parentId: '0',
    name: 'topic',
    routerPath: '/cloudable/topic',
    title: '专题',
    disabled: false,
    icon: 'el-icon-data-analysis',
    type: 1,
  },
  {
    id: '4',
    parentId: '0',
    name: 'about',
    routerPath: '/cloudable/about',
    title: '关于',
    disabled: false,
    icon: 'el-icon-s-custom',
    type: 3,
  },
]
